"""Added file to the song model

Revision ID: a705d4b5cb8a
Revises: 7091a84f4c63
Create Date: 2024-08-09 19:51:55.058229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a705d4b5cb8a'
down_revision: Union[str, None] = '7091a84f4c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('music_file_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'music_file_data')
    # ### end Alembic commands ###
