# Generated by Django 5.0.4 on 2024-07-30 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'First name must be at least 5 symbols')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'First name must be at least 2 symbols')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Last name must be at least 2 symbols')])),
                ('join_date', models.DateField()),
                ('popularity_score', models.PositiveIntegerField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.PositiveIntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('recommendedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_authors', related_query_name='recommended_authors', to='main_app.author')),
                ('followers', models.ManyToManyField(related_name='followed_authors', related_query_name='followed_authors', to='main_app.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'First name must be at least 2 symbols')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Last name must be at least 2 symbols')])),
                ('join_date', models.DateField()),
                ('popularity_score', models.PositiveIntegerField()),
                ('recommendedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('F', 'Fiction'), ('B', 'Biography'), ('SF', 'Science Fiction'), ('FA', 'Fantasy'), ('MY', 'Mystery'), ('TH', 'Thriller'), ('RO', 'Romance'), ('HO', 'Horror'), ('C', 'Criminal'), ('CL', "Children's literature")], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='books', to='main_app.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='books', to='main_app.publisher')),
            ],
        ),
    ]
