# Generated by Django 5.0.4 on 2024-07-30 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_book_genre_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'First name must be at least 2 symbols')]),
        ),
    ]
