# Generated by Django 5.0.4 on 2024-07-28 20:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5, message='Full name must be at least 5 symbols')])),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Nationality must be at least 2 symbols long')])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_of_experience', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('type', models.CharField(blank=True, choices=[('Head coach', 'Head coach'), ('Second coach', 'Second coach')], max_length=15, null=True)),
                ('legendary_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Premier League', 'Premier League'), ('Championship', 'Championship')], max_length=50, null=True)),
                ('prize_money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Arsenal', 'Arsenal'), ('Aston Villa', 'Aston Villa'), ('Bournemouth', 'Bournemouth'), ('Brentford', 'Brentford'), ('Brighton & Hove Albion', 'Brighton & Hove Albion'), ('Burnley', 'Burnley'), ('Chelsea', 'Chelsea'), ('Crystal Palace', 'Crystal Palace'), ('Everton', 'Everton'), ('Fulham', 'Fulham'), ('Liverpool', 'Liverpool'), ('Luton Town', 'Luton Town'), ('Manchester City', 'Manchester City'), ('Manchester United', 'Manchester United'), ('Newcastle United', 'Newcastle United'), ('Nottingham Forest', 'Nottingham Forest'), ('Sheffield United', 'Sheffield United'), ('Tottenham Hotspur', 'Tottenham Hotspur'), ('West Ham United', 'West Ham United'), ('Wolverhampton Wanderers', 'Wolverhampton Wanderers'), ('Birmingham City', 'Birmingham City'), ('Blackburn Rovers', 'Blackburn Rovers'), ('Bristol City', 'Bristol City'), ('Cardiff City', 'Cardiff City'), ('Coventry City', 'Coventry City'), ('Huddersfield Town', 'Huddersfield Town'), ('Hull City', 'Hull City'), ('Ipswich Town', 'Ipswich Town'), ('Leeds United', 'Leeds United'), ('Leicester City', 'Leicester City'), ('Middlesbrough', 'Middlesbrough'), ('Millwall', 'Millwall'), ('Norwich City', 'Norwich City'), ('Plymouth Argyle', 'Plymouth Argyle'), ('Preston North End', 'Preston North End'), ('Queens Park Rangers', 'Queens Park Rangers'), ('Rotherham United', 'Rotherham United'), ('Sheffield Wednesday', 'Sheffield Wednesday'), ('Southampton', 'Southampton'), ('Stoke City', 'Stoke City')], max_length=50, null=True)),
                ('fans', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stadium', models.CharField(max_length=50)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_coach', to='main_app.footballcoach')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_league', to='main_app.league')),
            ],
        ),
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5, message='Full name must be at least 5 symbols')])),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Nationality must be at least 2 symbols long')])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.CharField(blank=True, choices=[('GK', 'GK'), ('CB', 'CB'), ('LB', 'LB'), ('RB', 'RB'), ('LWB', 'LWB'), ('RWB', 'RWB'), ('CDM', 'CDM'), ('CM', 'CM'), ('CAM', 'CAM'), ('LM', 'LM'), ('RM', 'RM'), ('LW', 'LW'), ('RW', 'RW'), ('CF', 'CF'), ('ST', 'ST')], max_length=3, null=True)),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('club_legend', models.BooleanField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='main_app.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
